/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hotel.Jframe;

import com.mycompany.hotel.implDAO.HoaDonImplDAO;
import com.mycompany.hotel.model.Hoadon;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.DateTimeException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Computer
 */
public class QLHoaDon extends javax.swing.JInternalFrame {
    
    private DefaultTableModel tblModel;

    /**
     * Creates new form QLHoaDon
     *
     * @throws java.text.ParseException
     */
    public QLHoaDon() throws ParseException {
        initComponents();
        loadtbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datetxt = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoadon = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setTitle("Hóa đơn");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        datetxt.setDateFormatString("dd-MM-yyyy");

        jLabel1.setText("Ngày:");

        btnSearch.setText("Tìm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblHoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoadon);

        jButton1.setText("Xem hoa don:");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jButton1)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSearch)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sau = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat trc = new SimpleDateFormat("dd-MM-yyyy");
        Date date = datetxt.getDate();
        tblModel.setRowCount(0);
        JOptionPane.showMessageDialog(null, sau.format(date));
        HoaDonImplDAO xl = new HoaDonImplDAO();
        List<Hoadon> lst = xl.lstgetDate(sau.format(date));
        for (Hoadon h : lst) {
            try {
                Date d1 = sau.parse(h.getThoigiandat());
                Date d2 = sau.parse(h.getThoigiantra());
                String[] ar = {String.valueOf(h.getId()), trc.format(d1), trc.format(d2), String.valueOf(h.getP().getId()), String.valueOf(h.getP().getR().getSoPhong()), String.valueOf(h.getTongtien())};
                tblModel.addRow(ar);
            } catch (ParseException ex) {
                Logger.getLogger(QLHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tblHoadon.setModel(tblModel);
        

    }//GEN-LAST:event_btnSearchActionPerformed
    private int id_hd;
    private void tblHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoadonMouseClicked
        // TODO add your handling code here:
        int index = tblHoadon.getSelectedRow();
        if (index < 0) {
            return;
        }
        id_hd = Integer.parseInt(tblHoadon.getValueAt(index, 0).toString().trim());
        jButton1.setText("Xem hóa đơn: " + id_hd);
    }//GEN-LAST:event_tblHoadonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(id_hd>0){
            try {
                chitiethoadon1 ct = new chitiethoadon1(id_hd);
                ct.setVisible(true);
                ct.setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
                ct.setLocationRelativeTo(null);
            } catch (SQLException ex) {
                Logger.getLogger(QLHoaDon.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameDeactivated
    private void loadtbl() throws ParseException {
        tblModel = new DefaultTableModel();
        tblModel.addColumn("Id");
        tblModel.addColumn("thời gian đặt");
        tblModel.addColumn("thời gian trả");
        tblModel.addColumn("Mã phiếu phòng");
        tblModel.addColumn("Số phòng");
        tblModel.addColumn("Tổng tiền");
        SimpleDateFormat sau = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat trc = new SimpleDateFormat("dd-MM-yyyy");
        HoaDonImplDAO xl = new HoaDonImplDAO();
        List<Hoadon> lst = xl.lst();
        for (Hoadon h : lst) {
            Date d1 = sau.parse(h.getThoigiandat());
            Date d2 = sau.parse(h.getThoigiantra());
            String[] ar = {String.valueOf(h.getId()), trc.format(d1), trc.format(d2), String.valueOf(h.getP().getId()), String.valueOf(h.getP().getR().getSoPhong()), String.valueOf(h.getTongtien())};
            tblModel.addRow(ar);
        }
        tblHoadon.setModel(tblModel);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private com.toedter.calendar.JDateChooser datetxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoadon;
    // End of variables declaration//GEN-END:variables
}
