/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hotel.Jframe;

import com.mycompany.hotel.implDAO.KHImpDao;
import com.mycompany.hotel.model.KhachHang;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Computer
 */
public class QLKH extends javax.swing.JInternalFrame {

    /**
     * Creates new form QLKH
     */
    public QLKH() {
        initComponents();
        loadTBL();
        reset();
        setLocation(getWidth() / 2, getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKh = new javax.swing.JTable();
        btnSeach = new javax.swing.JButton();
        txttenKh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        txtIdKh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        jLabel4.setText("SĐT:");

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblKh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKh.setPreferredSize(new java.awt.Dimension(600, 100));
        tblKh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKh);

        btnSeach.setText("Tìm kiếm khách hàng");

        jLabel7.setText("Mã Khách ");
        jLabel7.setOpaque(true);

        jLabel1.setText("Tên khách");

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel3.setText("CCCD:");

        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCCCD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txtIdKh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttenKh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSdt)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnSeach)
                            .addGap(59, 59, 59)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttenKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeach)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        try {
            if (txtIdKh.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập mã khách hàng");
                return;
            }
            int id = Integer.parseInt(txtIdKh.getText());
            if (id > 0) {
                int check = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không", "Xóa", JOptionPane.WARNING_MESSAGE, JOptionPane.OK_CANCEL_OPTION);

                boolean success = check == JOptionPane.OK_OPTION ? new KHImpDao().delete(id) : false;

                if (success) {
                    reset();
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                    loadTBL();
                } else {
                    JOptionPane.showMessageDialog(null, "Thất bại");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblKhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhMouseClicked
        // TODO add your handling code here:
        int index = tblKh.getSelectedRow();
//        String ma = (String) tblKh.getValueAt(index, 0);
        if (index < 0) {
            return;
        }
        int id = (Integer) tblKh.getValueAt(index, 0);

        String cccd = (String) tblKh.getValueAt(index, 2);
        String sdt = (String) tblKh.getValueAt(index, 3);
        String ten = (String) tblKh.getValueAt(index, 1);
//        JOptionPane.showMessageDialog(null, id);

        KhachHang r = new KhachHang(cccd, sdt, id, ten);
        dolaidulieu(r);
    }//GEN-LAST:event_tblKhMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            String cccd = txtCCCD.getText();
            String sdt = txtSdt.getText();
            String ten = txttenKh.getText();

            KhachHang r = new KhachHang(cccd, sdt, 0, ten);
            KHImpDao xl = new KHImpDao();
            boolean success = xl.insert(r);
            if (success) {
                reset();
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                loadTBL();
            } else {
                JOptionPane.showMessageDialog(null, xl.getError());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtIdKh.getText());
            String cccd = txtCCCD.getText();
            String sdt = txtSdt.getText();
            String ten = txttenKh.getText();

            KhachHang r = new KhachHang(cccd, sdt, id, ten);
            KHImpDao xl = new KHImpDao();
            boolean success = xl.update(r);
            if (success) {
                reset();
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                loadTBL();
            } else {
                JOptionPane.showMessageDialog(null, xl.getError());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSeach;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKh;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtIdKh;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txttenKh;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        txtIdKh.setText("");
        txtIdKh.setEnabled(true);
        txtCCCD.setText("");
        txtSdt.setText("");
        txttenKh.setText("");
    }
    private List<KhachHang> lstKh;
    private DefaultTableModel tblModel;

    private void loadTBL() {
        tblModel = new DefaultTableModel();
        tblModel.addColumn("ID");
        tblModel.addColumn("Tên");
        tblModel.addColumn("CCCD");
        tblModel.addColumn("SĐT");
        tblKh.setModel(tblModel);

        lstKh = new KHImpDao().getAllKH();
        for (KhachHang kh : lstKh) {
            Vector v = new Vector();
            v.add(kh.getId());
            v.add(kh.getTen());
            v.add(kh.getCccd());
            v.add(kh.getSdt());
            tblModel.addRow(v);
        }
        tblKh.setModel(tblModel);
    }

    private void dolaidulieu(KhachHang r) {
        txtIdKh.setText(String.valueOf(r.getId()));
        txtIdKh.setEnabled(false);
        txtCCCD.setText(r.getCccd());
        txtSdt.setText(r.getSdt());
        txttenKh.setText(r.getTen());
    }
}
