/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hotel.Jframe;

import com.mycompany.hotel.implDAO.EmpImlDAO;
import com.mycompany.hotel.implDAO.RoleImpDAO;
import com.mycompany.hotel.model.Employee;
import com.mycompany.hotel.model.Role;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Computer
 */
public class QLNV extends javax.swing.JInternalFrame {

    /**
     * Creates new form QLNV
     */
    private DefaultComboBoxModel roleBoxModel;

    public QLNV() {
        initComponents();
        init_CB_role();
        loadTBL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        txttk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnSeach = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtmk = new javax.swing.JTextField();
        cbRole = new javax.swing.JComboBox<>();

        jLabel7.setText("Mã ND");
        jLabel7.setOpaque(true);

        jLabel1.setText("Quyền");

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel4.setText("Tài khoản");

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel3.setText("Họ và tên");

        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmp.setPreferredSize(new java.awt.Dimension(600, 100));
        tblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmp);

        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSeach.setText("Tìm kiếm NV");

        jLabel5.setText("Mật khẩu");

        cbRole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbRoleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtten, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txttk)
                                .addComponent(cbRole, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnSeach)
                                .addGap(59, 59, 59)
                                .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmk, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeach)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void init_CB_role() {
        roleBoxModel = new DefaultComboBoxModel();
        List<Role> lst = new RoleImpDAO().getAllRole();
        cbRole.addItem("Chọn quyền hạn");
        for (Role r : lst) {

            cbRole.addItem(r.getId() + " - " + r.getName());
        }

    }

    private int getIdRole() {
        int i = 0;
        if (cbRole.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "bạn vui lòng chọn quyền cho người dùng!!!");
        } else {
            String[] arr = cbRole.getSelectedItem().toString().split("-");

            i = Integer.parseInt(arr[0].toString().trim());
            JOptionPane.showMessageDialog(null, i);

        }
        return i;

    }

    ;
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handli ng code here:

        int role = getIdRole();
        String ten = txtten.getText();
        String tk = txttk.getText();
        String mk = txtmk.getText();
        String md5Hex = DigestUtils.md5Hex(mk).toUpperCase();
        Employee r = new Employee(new Role(role, "", ""), tk, md5Hex, 0, ten);

        boolean success = new EmpImlDAO().insert(r);
        if (success) {
            reset();
            JOptionPane.showMessageDialog(null, "Thêm thành công");
            loadTBL();
        } else {
            JOptionPane.showMessageDialog(null, "Thất bại");
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        try {
            if (txtId.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập mã khách hàng");
                return;
            }
            int id = Integer.parseInt(txtId.getText());
            if (id > 0) {
                int check = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không", "Xóa", JOptionPane.WARNING_MESSAGE, JOptionPane.OK_CANCEL_OPTION);

                boolean success = check == JOptionPane.OK_OPTION ? new EmpImlDAO().delete(id) : false;

                if (success) {
                    reset();
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                    loadTBL();
                } else {
                    JOptionPane.showMessageDialog(null, "Thất bại");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpMouseClicked
        // TODO add your handling code here:
        int index = tblEmp.getSelectedRow();
        int id = (Integer) tblEmp.getValueAt(index, 0);
        int role = (Integer) tblEmp.getValueAt(index, 5);
        String tenrole = (String) tblEmp.getValueAt(index, 1);
//
        String ten = (String) tblEmp.getValueAt(index, 2);
        String tk = (String) tblEmp.getValueAt(index, 3);
        String mk = (String) tblEmp.getValueAt(index, 4);
        //        JOptionPane.showMessageDialog(null, id);
//        JOptionPane.showMessageDialog(null, role);
        Employee r = new Employee(new Role(role, tenrole, ""), tk, mk, id, ten);
        dolaidulieu(r);
    }//GEN-LAST:event_tblEmpMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtId.getText());

            String ten = txtten.getText();
            String tk = txttk.getText();
            String mk = txtmk.getText();
            String md5Hex = DigestUtils.md5Hex(mk).toUpperCase();
            int role = getIdRole();

            Employee r = new Employee(new Role(role, "", ""), tk, md5Hex, id, ten);

            boolean success = new EmpImlDAO().update(r);
            if (success) {
                reset();
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                loadTBL();
            } else {
                JOptionPane.showMessageDialog(null, "Thất bại");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cbRoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRoleMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbRoleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSeach;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtmk;
    private javax.swing.JTextField txtten;
    private javax.swing.JTextField txttk;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        txtId.setText("");
        txtId.requestFocus();
        txtmk.setText("");
        txttk.setText("");
        txtten.setText("");
        cbRole.setSelectedIndex(0);
        txtId.setEnabled(true);

    }
    private DefaultTableModel tblModel;

    private void loadTBL() {
        tblModel = new DefaultTableModel();
        tblModel.addColumn("ID");
        tblModel.addColumn("Quyền hạn");
        tblModel.addColumn("Họ và tên");
        tblModel.addColumn("Tài khoản");
        tblModel.addColumn("Mật khẩu");
        tblModel.addColumn("role_id");

        tblEmp.setModel(tblModel);

        List<Employee> lst = new EmpImlDAO().getAllEmp();
        for (Employee e : lst) {
            Vector v = new Vector();
            v.add(e.getId());
            v.add(e.getR().getName());
            v.add(e.getTen());
            v.add(e.getTaikhoan());
            v.add("****************");
            v.add(e.getR().getId());

            tblModel.addRow(v);
        }
        tblEmp.setModel(tblModel);
        tblEmp.getColumnModel().getColumn(5).setMinWidth(0);
        tblEmp.getColumnModel().getColumn(5).setMaxWidth(0);
    }

    private void dolaidulieu(Employee r) {
        txtId.setText(String.valueOf(r.getId()));
        txtId.requestFocus();
        txtId.setEnabled(false);
        txtmk.setText(r.getMatkhau());
        txttk.setText(r.getTaikhoan());
        txtten.setText(r.getTen());
        String so = String.valueOf(r.getR().getId());
        String s = so + " - " + r.getR().getName();
        cbRole.setSelectedItem(s);
//        JOptionPane.showMessageDialog(null, r.toString());
    }
}
