/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hotel.Jframe;

import static com.mycompany.hotel.Jframe.Main.jDesktopPane1;
import com.mycompany.hotel.implDAO.RoomImpDao;
import com.mycompany.hotel.model.Room;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.List;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Computer
 */
public class QLRoomFrame extends javax.swing.JInternalFrame {
    
    private DefaultTableModel tbl;
    private Connection con = null;
    private List<Room> lst = null;

    /**
     * Creates new form QLRoomFrame
     */
    public QLRoomFrame() {
        initComponents();
        LoadGuiRoom();
        loadTBL();
        setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        if (JFLogin.id_role == 5) {
            QLRoomFrame.jTabbedPane5.setEnabledAt(1, true);
            
        }
        if (JFLogin.id_role == 1) {
            jTabbedPane5.setEnabledAt(1, false);
            
        }
    }
    
    private void LoadGuiRoom() {
        
        FlowLayout flowLayout = new FlowLayout();
        JPanel panel = new JPanel();
        panel.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getWidth());
        panel.setLayout(flowLayout);
        flowLayout.setAlignment(FlowLayout.LEFT);
        flowLayout.setHgap(15);
        flowLayout.setVgap(15);
        RoomImpDao rimlp = new RoomImpDao();
        List<Room> lst = rimlp.getAllRoom();
        for (Room r : lst) {
            String name = "Phòng " + String.valueOf(r.getSoPhong());
            JButton addButton = new JButton(name);
            addButton.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
            addButton.setActionCommand(String.valueOf(r.getSoPhong()));
            addButton.setName(String.valueOf(r.getId()));
            addButton.setPreferredSize(new Dimension(300, 250));
            addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/living-room (1).png"))); // NOI18N
            if (r.isStatus()) {
                addButton.setEnabled(false);
                addButton.setBackground(Color.RED);
                addButton.setOpaque(true);
            } else {
                addButton.setBackground(new java.awt.Color(102, 255, 102));
                addButton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        JButton nut = (JButton) e.getSource();
//                        JOptionPane.showMessageDialog(rootPane, nut.getName());
                        ThongtinDAtphong dp = new ThongtinDAtphong(nut.getName(), "Phòng " + nut.getActionCommand(), String.valueOf(JFLogin.id_nv));
                        dp.setVisible(true);
                    }
                });
                
            }
            panel.add(addButton);
            
        }
        jPanel1.add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNameR = new javax.swing.JTextField();
        txtSoTang = new javax.swing.JTextField();
        txtSoGiuong = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnAddRoom = new javax.swing.JButton();
        btnUpdateRoom = new javax.swing.JButton();
        btnDeleteRoom = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSeachRom = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtIdR = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Quản lý phòng");
        setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Quản lý phòng", jPanel1);

        jLabel1.setText("Tên phòng");

        jLabel3.setText("Số tầng");

        jLabel4.setText("Số giường");

        jLabel5.setText("Giá");

        jLabel6.setText("Trạng thái");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Còn");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Đã đặt");

        btnAddRoom.setText("Thêm");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        btnUpdateRoom.setText("Sửa");
        btnUpdateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRoomActionPerformed(evt);
            }
        });

        btnDeleteRoom.setText("Xóa");
        btnDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoomActionPerformed(evt);
            }
        });

        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSeachRom.setText("Tìm kiếm phòng");

        jLabel7.setText("Mã phòng");
        jLabel7.setOpaque(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(79, 79, 79)
                                .addComponent(jRadioButton2))
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSoTang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txtIdR, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameR, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoGiuong)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnSeachRom)
                            .addGap(59, 59, 59)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnUpdateRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtIdR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNameR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSoTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSoGiuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddRoom)
                            .addComponent(btnUpdateRoom)
                            .addComponent(btnDeleteRoom))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSeachRom)
                            .addComponent(btnReset))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane5.addTab("Danh sách phòng", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
        

    }//GEN-LAST:event_btnResetActionPerformed
    private void dolaidulieu(Room r) {
        txtIdR.setText(String.valueOf(r.getId()));
        txtGia.setText(String.valueOf(r.getGia()));
        txtNameR.setText(String.valueOf(r.getSoPhong()));
        txtSoGiuong.setText(String.valueOf(r.getSoGiuong()));
        txtSoTang.setText(String.valueOf(r.getSoTang()));
        txtIdR.setEnabled(false);
        if (r.isStatus()) {
            jRadioButton2.setSelected(true);
            
            jRadioButton1.setSelected(false);
        } else {
            jRadioButton2.setSelected(false);
            jRadioButton1.setSelected(true);
            
        }
    }
    
    private void reset() {
        txtIdR.setText("");
        txtGia.setText("");
        txtNameR.setText("");
        txtSoGiuong.setText("");
        txtSoTang.setText("");
        txtNameR.setText("");
        txtNameR.requestFocus();
        txtIdR.setEnabled(true);
        buttonGroup1.clearSelection();
        loadTBL();
    }
    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        // TODO add your handling code here:
        try {
            int sophong = Integer.parseInt(txtNameR.getText());
            int sotang = Integer.parseInt(txtSoTang.getText());
            double gia = Double.parseDouble(txtGia.getText());
            int sogiuong = Integer.parseInt(txtSoGiuong.getText());
            boolean isCheck = false;
            if (jRadioButton1.isSelected()) {
                isCheck = false;
            }
            if (jRadioButton2.isSelected()) {
                isCheck = true;
            }
            Room r = new Room();
            r.setSoPhong(sophong);
            r.setSoTang(sotang);
            r.setSoGiuong(sogiuong);
            r.setGia(gia);
            r.setStatus(isCheck);
            boolean success = new RoomImpDao().insert(r);
            if (success) {
                reset();
                JOptionPane.showMessageDialog(null, "THêm thành công");
                loadTBL();
            } else {
                JOptionPane.showMessageDialog(null, "Thất bại");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnUpdateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRoomActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtIdR.getText());
            int sophong = Integer.parseInt(txtNameR.getText());
            int sotang = Integer.parseInt(txtSoTang.getText());
            double gia = Double.parseDouble(txtGia.getText());
            int sogiuong = Integer.parseInt(txtSoGiuong.getText());
            boolean isCheck = false;
            if (jRadioButton1.isSelected()) {
                isCheck = false;
            }
            if (jRadioButton2.isSelected()) {
                isCheck = true;
            }
            Room r = new Room();
            r.setId(id);
            r.setSoPhong(sophong);
            r.setSoTang(sotang);
            r.setSoGiuong(sogiuong);
            r.setGia(gia);
            r.setStatus(isCheck);
            boolean success = new RoomImpDao().update(r);
            if (success) {
                reset();
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                loadTBL();
            } else {
                JOptionPane.showMessageDialog(null, "Thất bại");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }//GEN-LAST:event_btnUpdateRoomActionPerformed

    private void btnDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoomActionPerformed
        // TODO add your handling code here:

        try {
            if (txtIdR.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập mã phòng");
                return;
            }
            int id = Integer.parseInt(txtIdR.getText());
            if (id > 0) {
                int check = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không", "Xóa", JOptionPane.WARNING_MESSAGE, JOptionPane.OK_CANCEL_OPTION);
                
                if (check == JOptionPane.OK_OPTION) {
                    boolean success = new RoomImpDao().delete(id);
                    
                    if (success) {
                        reset();
                        JOptionPane.showMessageDialog(null, "Xoa thành công");
                        loadTBL();
                    } else {
                        JOptionPane.showMessageDialog(null, "Thất bại");
                    }
                } else {
                    return;
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }//GEN-LAST:event_btnDeleteRoomActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        if(index<0){
            return;
        }
        int id = Integer.parseInt(jTable1.getValueAt(index, 0).toString().trim());
        int sophong = Integer.parseInt(jTable1.getValueAt(index, 1).toString().trim());
        int sotang = Integer.parseInt(jTable1.getValueAt(index, 2).toString().trim());
        int sogiuong = Integer.parseInt(jTable1.getValueAt(index, 3).toString().trim());
        double gia = Double.parseDouble(jTable1.getValueAt(index, 4).toString().trim());
        boolean c = false;
        if (jTable1.getValueAt(index, 5).toString().trim().equals("Còn")) {
            c = false;
        } else {
            c = true;
        }
        //        JOptionPane.showMessageDialog(null, id);

        Room r = new Room(id, sophong, sotang, sogiuong, gia, c);
        dolaidulieu(r);
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void loadTBL() {
        
        lst = new RoomImpDao().getAllRoom();
        tbl = new DefaultTableModel();
        tbl.addColumn("Mã Phòng");
        tbl.addColumn("Số Phòng");
        tbl.addColumn("Số Tầng");
        tbl.addColumn("Số Giường");
        tbl.addColumn("Giá");
        tbl.addColumn("Tình Trạng");
        jTable1.setModel(tbl);
        
        for (Room r : lst) {
            String [] arrom = {String.valueOf(r.getId()),String.valueOf(r.getSoPhong()),String.valueOf(r.getSoTang()),String.valueOf(r.getSoGiuong()),String.valueOf(r.getGia()),r.isStatus() ? "Đã đặt" : "Còn"};
          
            tbl.addRow(arrom);
        }
        jTable1.setModel(tbl);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnDeleteRoom;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSeachRom;
    private javax.swing.JButton btnUpdateRoom;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtIdR;
    private javax.swing.JTextField txtNameR;
    private javax.swing.JTextField txtSoGiuong;
    private javax.swing.JTextField txtSoTang;
    // End of variables declaration//GEN-END:variables
}
