/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hotel.Jframe;

import com.mycompany.hotel.implDAO.ThietbiImpDAO;
import com.mycompany.hotel.model.ThietBi;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Computer
 */
public class QLTB extends javax.swing.JInternalFrame {
private DefaultTableModel tblModel;
    private List<ThietBi> lstDV;
    /**
     * Creates new form QLDV
     */
    public QLTB() {
        initComponents();
        loadTBL();
        reset();
        setLocation(getWidth()/2, getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txttenDV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDV = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnSeach = new javax.swing.JButton();
        jSpinField1 = new com.toedter.components.JSpinField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtdonvi = new javax.swing.JTextField();

        setClosable(true);

        jLabel7.setText("Mã TB");
        jLabel7.setOpaque(true);

        jLabel1.setText("Tên TB");

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel4.setText("Status");

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel3.setText("Số lượng");

        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDV.setPreferredSize(new java.awt.Dimension(600, 100));
        tblDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDV);

        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSeach.setText("Tìm kiếm thiết bị");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Hoạt động");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Hỏng");

        jLabel2.setText("Đơn vị");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txttenDV, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addComponent(jSpinField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtdonvi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnSeach)
                            .addGap(59, 59, 59)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeach)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
//            int id = Integer.parseInt(txtId.getText());
            String ten = txttenDV.getText();
            String donvi = txtdonvi.getText();
            int sl = jSpinField1.getValue();
            boolean stt = false;
            if (jRadioButton1.isSelected()) {
                stt = true;
            }
            if (jRadioButton2.isSelected()) {
                stt = false;
            }
            ThietBi r = new ThietBi(0, ten, donvi, sl, stt);

            boolean success = new ThietbiImpDAO().insert(r);
            if (success) {
                reset();
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                loadTBL();
            } else {
                JOptionPane.showMessageDialog(null, "Thất bại");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        try {
            if (txtId.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập mã khách hàng");
                return;
            }
            int id = Integer.parseInt(txtId.getText());
            if (id > 0) {
                int check = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không", "Xóa", JOptionPane.WARNING_MESSAGE, JOptionPane.OK_CANCEL_OPTION);

                boolean success = check == JOptionPane.OK_OPTION ? new ThietbiImpDAO().delete(id) : false;

                if (success) {
                    reset();
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                    loadTBL();
                } else {
                    JOptionPane.showMessageDialog(null, "Thất bại");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDVMouseClicked
        // TODO add your handling code here:
        int index = tblDV.getSelectedRow();
        int id = (Integer) tblDV.getValueAt(index, 0);

        String ten = (String) tblDV.getValueAt(index, 1);
        String donvi = (String) tblDV.getValueAt(index, 2);
        int sl = (Integer) tblDV.getValueAt(index, 3);
        boolean stt = tblDV.getValueAt(index, 4).equals("Hoạt động") ? true : false;
        //        JOptionPane.showMessageDialog(null, id);

        ThietBi r = new ThietBi(id, ten, donvi, sl, stt);
        dolaidulieu(r);
    }//GEN-LAST:event_tblDVMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtId.getText());
            String ten = txttenDV.getText();
            String donvi = txtdonvi.getText();
            int sl = jSpinField1.getValue();
            boolean stt = false;
            if (jRadioButton1.isSelected()) {
                stt = true;
            }
            if (jRadioButton2.isSelected()) {
                stt = false;
            }
            ThietBi r = new ThietBi(id, ten, donvi, sl, stt);
            boolean success = new ThietbiImpDAO().update(r);
            if (success) {
                reset();
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                loadTBL();
            } else {
                JOptionPane.showMessageDialog(null, "Thất bại");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSeach;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTable tblDV;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtdonvi;
    private javax.swing.JTextField txttenDV;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        txtId.setText("");
        txttenDV.setText("");
        txtdonvi.setText("");
        jSpinField1.setValue(0);
        buttonGroup1.clearSelection();

    }
    

    private void loadTBL() {
        tblModel = new DefaultTableModel();
        tblModel.addColumn("ID");
        tblModel.addColumn("Tên");
        tblModel.addColumn("Đơn vị");
        tblModel.addColumn("Số lượng");
        tblModel.addColumn("Trạng thái");

        tblDV.setModel(tblModel);

        lstDV = new ThietbiImpDAO().getAllDV();
        for (ThietBi dv : lstDV) {
            Vector v = new Vector();
            v.add(dv.getId());
            v.add(dv.getTen());
            v.add(dv.getDonvi());
            v.add(dv.getSoluong());
            v.add(dv.isStatus() ? "Hoạt động" : "Hỏng");

            tblModel.addRow(v);
        }
        tblDV.setModel(tblModel);
    }

    private void dolaidulieu(ThietBi r) {
        txtId.setText(String.valueOf(r.getId()));
        txttenDV.setText(r.getTen());
        txtdonvi.setText(String.valueOf(r.getDonvi()));
        jSpinField1.setValue(r.getSoluong());
        if (r.isStatus()) {
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);

        } else {
            jRadioButton2.setSelected(true);
            jRadioButton1.setSelected(false);
        }

    }
}
