/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hotel.Jframe;

import com.itextpdf.io.font.FontConstants;
import com.itextpdf.kernel.color.Color;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.LineSeparator;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.element.Text;
import com.mycompany.hotel.Help.Database;
import com.mycompany.hotel.implDAO.DatPhongImpDAO;
import com.mycompany.hotel.implDAO.HoaDonImplDAO;
import com.mycompany.hotel.implDAO.RoomImpDao;
import com.mycompany.hotel.implDAO.chitiethoadonimplDAO;
import com.mycompany.hotel.model.Dichvu;
import com.mycompany.hotel.model.Hoadon;
import com.mycompany.hotel.model.Phieudatphong;
import com.mycompany.hotel.model.chitiethoadon;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.draw.DashedLine;
import com.itextpdf.kernel.pdf.canvas.draw.SolidLine;
import com.itextpdf.layout.element.AreaBreak;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.element.LineSeparator;

/**
 *
 * @author Computer
 */
public class QLTT extends javax.swing.JInternalFrame {

    DecimalFormat df = new DecimalFormat("###,###,###");

    private DefaultTableModel tblTT;
    int id_datphong;

    /**
     * Creates new form QLTT
     */
    public QLTT() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCheck = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDR = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDateBefore = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtdateEnd = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        songayo = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        txtcccd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        tblCheck.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCheckMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCheck);

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("HOTEL CHECKOUT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Số phòng:");

        txtIDR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnTim.setBackground(new java.awt.Color(153, 51, 0));
        btnTim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 102, 51));
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên khách");

        jLabel4.setText("Giá phòng");

        jLabel5.setText("Ngày đặt");

        jLabel6.setText("Ngày trả");

        jLabel7.setText("Số điện thoại");

        jLabel8.setText("CCCD");

        jLabel9.setText("Tổng tiền");

        jLabel10.setText("Số ngày ở:");

        jButton1.setText("LÀM MỚI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setText("CHECKOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(txtGia, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                            .addComponent(txtName))
                                        .addGap(79, 79, 79)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(143, 143, 143))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(132, 132, 132))
                                            .addComponent(txtDateBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(songayo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIDR, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(128, 128, 128))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(134, 134, 134))
                                            .addComponent(txtdateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(124, 124, 124)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel7)
                                                .addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtsdt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(92, 92, 92)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(16, 16, 16)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(txtDateBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(songayo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtdateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        try {
            DatPhongImpDAO xl = new DatPhongImpDAO();
            Phieudatphong p = xl.searchNameRoom(txtIDR.getText());
            dodulieu(p);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void tblCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCheckMouseClicked
        // TODO add your handling code here:
        int index = tblCheck.getSelectedRow();
//        int sp = (int) tblCheck.getValueAt(index, 4);
//        System.out.println(sp);
        if (index < 0) {
            return;
        }
        if (index >= 0) {
            try {

                DatPhongImpDAO xl = new DatPhongImpDAO();
                Phieudatphong p = xl.searchNameRoom(String.valueOf(tblCheck.getValueAt(index, 4)));

                dodulieu(p);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        txtIDR.setText((String) tblCheck.getValueAt(index, 4));

    }//GEN-LAST:event_tblCheckMouseClicked
    private void reset() {
        txtIDR.setText("");
        txtGia.setText("");
        txtsdt.setText("");

        txtName.setText("");
        txtcccd.setText("");
        txtDateBefore.setText("");
        txtdateEnd.setText("");

        songayo.setText("");
        total.setText("");
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (id_datphong == 0) {
            JOptionPane.showMessageDialog(null, "Vui long nhap thong tin!!!");
            return;
        }
        int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn thanh toán", "Thanh Toán!!!", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            try {
                new DatPhongImpDAO().UpdatePhieuSTT(id_datphong, 2);
                new RoomImpDao().updateSTT(0, txtIDR.getText());
                HoaDonImplDAO hdiDao = new HoaDonImplDAO();
                Hoadon hoadon = new Hoadon();
                Phieudatphong p = new Phieudatphong();
                p.setId(id_datphong);
                hoadon.setP(p);
                SimpleDateFormat sau = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat trc = new SimpleDateFormat("dd-MM-yyyy");

                Date d1 = trc.parse(txtDateBefore.getText());
                Date d2 = trc.parse(txtdateEnd.getText());

                System.out.println("" + sau.format(d1));
                hoadon.setThoigiandat(sau.format(d1));
                System.out.println("" + sau.format(d2));

                hoadon.setThoigiantra(sau.format(d2));
                hoadon.setTongtien(Double.parseDouble(total.getText()));

                boolean succ = hdiDao.insert_hoadon(hoadon);
                if (succ) {
                    try {
                        int id_hd = hdiDao.getId_gennerate();

                        //Làm tiếp Lưu chitiet hóa đơn và sử dụng dịch vụ
                        List<Dichvu> lstDV = new DatPhongImpDAO().getSDDichvu(id_datphong);
                        if (lstDV.size() > 0) {
                            for (Dichvu v : lstDV) {
                                chitiethoadon ct = new chitiethoadon();
                                Hoadon hd = new Hoadon();
                                hd.setId(id_hd);
                                ct.setH(hd);
                                Dichvu n = new Dichvu();
                                n.setId(v.getId());
                                ct.setDv(n);
                                ct.setSoluong(v.getSoluong());
                                boolean scc = new chitiethoadonimplDAO().insert(ct);
                                if (scc) {
                                    System.out.println("Thanh cong tao hoa don");

                                } else {
                                    System.out.println("Lỗi tao hoa don");
                                }
                            }

                        }else{
                            chitiethoadon ct = new chitiethoadon();
                                Hoadon hd = new Hoadon();
                                hd.setId(id_hd);
                                ct.setH(hd);
                                Dichvu n = new Dichvu();
                                n.setId(0);
                                ct.setDv(n);
                                ct.setSoluong(0);
                                boolean scc = new chitiethoadonimplDAO().insert(ct);
                                if (scc) {
                                    System.out.println("Thanh cong tao hoa don");

                                } else {
                                    System.out.println("Lỗi tao hoa don");
                                }
                        }
                        inhoadon(id_hd);
                        if (new File("E:\\" + id_hd + ".pdf").exists()) {
                            int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn in hóa đơn không", "Thanh Toán!!!", JOptionPane.YES_NO_OPTION);
                            if (a == JOptionPane.YES_OPTION) {
                                loadTable();
                                Process ps = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler E:\\" + id_hd + ".pdf");
                            } else {
                                loadTable();
                                return;
                            }
                        }
                        reset();
                    } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                    } catch (IOException ex) {
                        Logger.getLogger(QLTT.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(QLTT.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reset();

    }//GEN-LAST:event_jButton1ActionPerformed
    private void inhoadon(int id) throws SQLException {
        String path = "E:\\";
        String sql = "select * from chitiethoadon ct INNER join hoadon hd on ct.mahd = hd.id INNER JOIN dichvu dv on ct.madv = dv.id INNER JOIN phieudatphong dp on hd.maPhieuDatPhong = dp.id INNER JOIN phong p on dp.maPhong = p.id where hd.id=" + id;
        Database db = new Database();

        PdfWriter pdfWriter;
        try {
            Connection con = db.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            pdfWriter = new PdfWriter(new FileOutputStream(path + id + ".pdf"));
            PdfDocument pdfDocument = new PdfDocument(pdfWriter);
            pdfDocument.addNewPage();
            PdfFont font = PdfFontFactory.createFont(FontConstants.TIMES_BOLD);
            com.itextpdf.layout.Style header = new com.itextpdf.layout.Style();
            header.setTextAlignment(TextAlignment.CENTER).setFontSize(15f);
            Text t1 = new Text("Hoa don thanh toan").setFont(font);
            Paragraph p1 = new Paragraph(t1).addStyle(header);

            Paragraph p3 = new Paragraph("BILL ID: " + id);
            String dt = df.format(Double.parseDouble(txtsdt.getText()));
            Paragraph p4 = new Paragraph("Fullname: " + txtName.getText() + " \nPhone: " + dt + " \nCCCD: " + txtcccd.getText());
            Text t2 = new Text("Phieu dat phong: " + id_datphong).setFont(font);
            Paragraph p8 = new Paragraph("So phong: " + txtIDR.getText());
            String gp = df.format(Double.parseDouble(txtGia.getText())) + " VND";
            Paragraph p9 = new Paragraph("Gia phong: " + gp);
            Paragraph p10 = new Paragraph("Ngay dat phong: " + txtDateBefore.getText());
            Paragraph p11 = new Paragraph("Ngay tra phong: " + txtdateEnd.getText());
            Paragraph p12 = new Paragraph("So ngay o: " + songayo.getText());
            header = new com.itextpdf.layout.Style();
            header.setTextAlignment(TextAlignment.LEFT).setFontSize(14f);
            Paragraph p5 = new Paragraph(t2).addStyle(header);
            Paragraph p6 = new Paragraph("Su dung dich vu").setFont(font).addStyle(header);
            //table
            float columnWID[] = {150f, 150f, 150f, 100f};
            Table tablePDH = new Table(columnWID).setMarginBottom(10f);
            tablePDH.addCell(new Cell().add("Ma dich vu").setFont(font));
            tablePDH.addCell(new Cell().add("Ten dich vu").setFont(font));
            tablePDH.addCell(new Cell().add("Gia").setFont(font));
            tablePDH.addCell(new Cell().add("So luong").setFont(font));

            while (rs.next()) {
                tablePDH.addCell(new Cell().add(String.valueOf(rs.getInt("dv.id"))).setFont(font));
                tablePDH.addCell(new Cell().add(rs.getString("dv.tendichvu")).setFont(font));
                String tien = df.format(rs.getDouble("dv.gia")) + " VND";
                tablePDH.addCell(new Cell().add(tien).setFont(font));
                tablePDH.addCell(new Cell().add(String.valueOf(rs.getInt("ct.soluong"))).setFont(font));
            }
            String tongti = df.format(Double.parseDouble(total.getText())) + " VND";
            Paragraph tong = new Paragraph("Tong tien: " + tongti).setTextAlignment(TextAlignment.RIGHT);
            com.itextpdf.layout.Document doc = new com.itextpdf.layout.Document(pdfDocument);
            doc.add(p1);
            LineSeparator separator = new LineSeparator(new SolidLine(3f)); // Customize line style
            separator.setBackgroundColor(Color.LIGHT_GRAY); // Customize line color
            doc.add(separator);
            doc.add(p3);
            doc.add(p4);
            doc.add(separator);
            doc.add(p5);
            doc.add(p8);
            doc.add(p9);
            doc.add(p10);
            doc.add(p11);
            doc.add(p12);

            doc.add(separator);
            doc.add(p6);

            doc.add(tablePDH);
            doc.add(separator);
            doc.add(tong);
            doc.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(QLTT.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QLTT.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void dodulieu(Phieudatphong p) throws ParseException, SQLException {
//        txtIDR.setText(String.valueOf(p.getId()));
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date date1 = dt.parse(p.getThoigiandat());
        SimpleDateFormat outdateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date2 = new Date();
        txtGia.setText(String.valueOf(p.getR().getGia()));
        txtsdt.setText(p.getKh().getSdt());

        String d1 = new SimpleDateFormat("YYYY-MM-dd").format(date1);
        String d2 = new SimpleDateFormat("YYYY-MM-dd").format(date2);

        txtName.setText(p.getKh().getTen());
        txtcccd.setText(p.getKh().getCccd());
        txtDateBefore.setText(outdateFormat.format(date1));
        txtdateEnd.setText(outdateFormat.format(new Date()));

        LocalDate ngay1 = LocalDate.parse(d1);
        LocalDate ngay2 = LocalDate.parse(d2);
        long khoangcach = ChronoUnit.DAYS.between(ngay1, ngay2);
        if (khoangcach == 0) {
            khoangcach = 1;
            songayo.setText(String.valueOf(1));

        }
        songayo.setText(String.valueOf(khoangcach));

        double gia = 0;
        gia = new DatPhongImpDAO().MoneyService(p.getId());
        total.setText(String.valueOf((p.getR().getGia() * khoangcach) + gia));

        id_datphong = p.getId();
    }

    private void loadTable() {
        tblTT = new DefaultTableModel();
        tblTT.addColumn("ID");
        tblTT.addColumn("Tên Khách");
        tblTT.addColumn("Số điện thoại");
        tblTT.addColumn("CCCD");
        tblTT.addColumn("Số phòng");
        tblTT.addColumn("Giá");
        tblCheck.setModel(tblTT);
        DatPhongImpDAO xl = new DatPhongImpDAO();
        List<Phieudatphong> lst = xl.getAllPD();
        for (Phieudatphong p : lst) {
            String[] Row = {String.valueOf(p.getId()), p.getKh().getTen(), p.getKh().getSdt(), p.getKh().getCccd(), String.valueOf(p.getR().getSoPhong()), String.valueOf(p.getR().getGia())};
            tblTT.addRow(Row);
        }
        tblCheck.setModel(tblTT);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField songayo;
    private javax.swing.JTable tblCheck;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txtDateBefore;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtIDR;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtcccd;
    private javax.swing.JTextField txtdateEnd;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
